unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
protect_all_forms: true
log: true
element_name: first_name
time_limit: 0
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  contact_message_contact_form_form: false
  contact_message_feedback_form: false
  contact_message_personal_form: false
  contact_message_website_contact__form: false
  node_article_form: false
  node_blog_form: false
  node_forum_form: false
  node_gallery_form: false
  node_page_form: false
  node_simplenews_issue_form: false
  node_video_form: false
  comment_comment_form: false
  comment_comment_forum_form: false
_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
