schemas:
  bootstrap: 8000
  mobile: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: 'public://favicon_0_0.ico'
  url: ''
  use_default: 0
features:
  comment_user_picture: 0
  comment_user_verification: 0
  favicon: 1
  node_user_picture: 0
logo:
  path: 'public://galapagos2_logo_1.png'
  url: ''
  use_default: 0
cdn_provider: ''
region_wells:
  header: ''
  header_top: ''
  header_bottom: ''
  highlighted: ''
  help: ''
  breadcrumb: ''
  content: ''
  content_bottom: ''
  footer: ''
  footer_bottom: ''
  page_bottom_fixed: ''
table_responsive: '-1'
modal_enabled: 0
popover_enabled: 0
tooltip_enabled: 0
table: ''
button_colorize: 0
button_iconize: 0
breadcrumb_home: 1
