cdn_provider: ''
_core:
  default_config_hash: _5qrDuRmWmRVjW00si3U1s1NrgrocA4N653EYGRfgEE
schemas:
  bootstrap: 8000
  mwakilish: 8000
table_responsive: '-1'
popover_enabled: 0
tooltip_enabled: 0
table: ''
breadcrumb_home: 1
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  header_nav: ''
  highlighted: ''
  help: ''
  breadcrumb: ''
  top_content: ''
  content: ''
  content_bottom: ''
  sidebar_first: ''
  sidebar_second: ''
  footer_top: ''
  footer_middle: ''
  footer: ''
  page_bottom_fixed: ''
favicon:
  mimetype: image/vnd.microsoft.icon
  path: 'public://favicon_0.ico'
  url: 'http://www.mwakilishi.com/sites/default/files/favicon.ico'
  use_default: false
features:
  comment_user_picture: false
  comment_user_verification: false
  favicon: true
  node_user_picture: false
logo:
  path: 'public://galapagos2_logo_1.png'
  url: ''
  use_default: false
