max_links: 50
cron_generate: true
remove_duplicates: true
skip_untranslated: false
batch_process_limit: 10
enabled_entity_types:
  - node
  - taxonomy_term
_core:
  default_config_hash: 8k2nJ3kHjGVhNYkfxevQzneu__VHph2Nb1LrZVV9fms
base_url: ''
