favicon:
  mimetype: image/vnd.microsoft.icon
  path: 'public://galapagos2_favicon_0.ico'
  url: ''
  use_default: false
features:
  comment_user_picture: false
  comment_user_verification: false
  favicon: false
  node_user_picture: false
logo:
  path: 'public://galapagos2_logo_1.png'
  url: ''
  use_default: false
