<?php
// $Id: smsbulk_example.module,v 1.1.2.2 2009/06/29 21:05:25 gunzip Exp $

/**
 * @file
 *
 *  SMS bulk sender example: usage example of smsbulk hooks
 */

/**
 * Implementation of hook_smsbulk_sms_sent().
 *  logs if sending was successful
 */
function smsbulk_example_smsbulk_sms_sent($params) {
  if ($params['success']) {
    $msg = t('[%oid] Successfully sent "%message" to %number');
    $arg = array('%oid' => $params['oid'], '%number' => $params['number'], '%message' => $params['text']);
    drupal_set_message(t($msg, $arg));
    watchdog('actions', $msg, $arg, WATCHDOG_NOTICE);
  }
  else {
    $msg = t('[%oid] Failed sending SMS');
    $arg['%oid'] = $params['oid'];
    if (!empty($params['number'])) {
      $msg .= t(' to %number');
      $arg['%number'] = $params['number'];
    }
    $msg .= ': '. $params['error'];
    drupal_set_message(t($msg, $arg), 'error');
    watchdog('actions', $msg, $arg, WATCHDOG_ERROR);
  }
}

/**
 * Implementation of hook_smsbulk_number_validate().
 *  example for "validating" italian numbers
 *
 * Smsframework module already provides a hook for validating numbers
 * but the usage is limited to the current gateway module.
 * Here we want possibly chained validation functions that do not
 * depend from the current gateway.
 */
function smsbulk_example_smsbulk_validate_number($number) {
  $number = preg_replace('/[^0-9]+/', '', $number);
  if (empty($number)) {
    return FALSE;
  }
  return $number;
}
