definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  standard__front_page:
    enabled: true
    menu_name: main
    parent: ''
    expanded: false
    weight: -50
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__11':
    weight: -47
    menu_name: categories
    parent: ''
    enabled: true
    expanded: false
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__9':
    weight: -41
    menu_name: categories
    parent: ''
    expanded: false
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__31':
    weight: -42
    menu_name: categories
    parent: ''
    expanded: false
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__10':
    weight: -49
    menu_name: categories
    parent: ''
    expanded: false
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__24':
    weight: -40
    menu_name: categories
    parent: ''
    expanded: false
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__8':
    weight: -39
    menu_name: categories
    parent: ''
    expanded: false
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__32':
    weight: -38
    menu_name: categories
    parent: ''
    expanded: false
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__12':
    weight: -48
    menu_name: categories
    parent: ''
    expanded: false
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__13':
    weight: -50
    menu_name: categories
    parent: ''
    expanded: false
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__19':
    weight: -46
    menu_name: categories
    parent: ''
    expanded: false
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__28':
    weight: -43
    menu_name: categories
    parent: ''
    expanded: false
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__22':
    weight: -44
    menu_name: categories
    parent: ''
    expanded: false
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__30':
    weight: -37
    menu_name: categories
    parent: ''
    expanded: false
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__29':
    weight: -45
    menu_name: categories
    parent: ''
    expanded: false
    enabled: true
