module:
  action: 0
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  aggregator: 0
  automated_cron: 0
  back_to_top: 0
  block: 0
  block_class: 0
  block_content: 0
  blocktabs: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  colorbox: 0
  comment: 0
  components: 0
  config: 0
  config_update: 0
  contact: 0
  contextual: 0
  ctools: 0
  custom_fb_inter: 0
  datetime: 0
  dblog: 0
  ds_extras: 0
  ds_switch_view_mode: 0
  dynamic_page_cache: 0
  editor: 0
  entity_clone: 0
  entity_pager: 0
  entity_submenu_block: 0
  features: 0
  features_ui: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  masonry: 0
  masonry_views: 0
  menu_link_attributes: 0
  menu_ui: 0
  metatag: 0
  metatag_google_plus: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  monte_features: 0
  node: 0
  node_clone: 0
  options: 0
  owl: 0
  page_cache: 0
  path: 0
  rdf: 0
  rest: 0
  search: 0
  serialization: 0
  shortcut: 0
  simple_sitemap: 0
  simplenews: 0
  sky_alt: 0
  sky_head: 0
  statistics: 0
  statistics_counter: 0
  system: 0
  taxonomy: 0
  taxonomy_menu: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  typed_data: 0
  update: 0
  user: 0
  views_ifempty: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  ds: 1
  extlink: 1
  forum: 1
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  bootstrap: 0
  bartik: 0
  mwakilishi: 0
  mobile: 0
  mwakilishii: 0
profile: standard
