page_id: '642304705934958'
access_token: EAACEdEose0cBADAuAXfDaz4WPuKXxiZA4BM7NeljuaRopjbNhhogNGk0uxfgaU8XDoUSvg1SipHHMsLS0QTZBbdeR3xyzFY70VXbF32cN2r6KIHJCor4tzZA6ls1VyN3xZC5TUZALUupmLrA9jh3049mnLYSFt9hOj9Nls66FReJgnO6jyGN9OpzvOdfa4xKf63itZBcBvOAZDZD
last_update: 1505193309
content_types:
  article: article
  blog: blog
  ad: 0
  audio2: 0
  faq: 0
  feedback: 0
  forum: 0
  message_board: 0
  page: 0
  poll: 0
  story: 0
  type: 0
  video: 0
  video_feed: 0
  webform: 0
_core:
  default_config_hash: pVzTHdHJYzwXZnpL12BH52IWv5XObl2cMc-n1jTGOgk
