extlink_include: ''
extlink_exclude: ''
extlink_alert_text: 'You are about to leave Mwakilishi.com. Are you sure you want to proceed?'
extlink_alert: false
extlink_target: false
extlink_subdomains: false
extlink_mailto_class: '0'
extlink_img_class: false
extlink_class: '0'
extlink_css_exclude: ''
extlink_css_explicit: ''
