schemas:
  bootstrap: 8000
  mwakilishi: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: 'public://favicon_1.ico'
  url: 'http://www.mwakilishi.com/sites/default/files/galapagos2_favicon_0.ico'
  use_default: 0
features:
  comment_user_picture: 0
  comment_user_verification: 0
  favicon: 1
  node_user_picture: 0
logo:
  path: 'public://galapagos2_logo_1.png'
  url: ''
  use_default: 0
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  header_banner: ''
  header_nav: ''
  header_bottom: ''
  highlighted: ''
  help: ''
  breadcrumb: ''
  content_top: ''
  content: ''
  content_bottom: ''
  sidebar_first: ''
  sidebar_second: ''
  footer: ''
  page_bottom_fixed: ''
table_responsive: '-1'
table: ''
cdn_provider: ''
breadcrumb_home: 1
popover_enabled: 0
tooltip_enabled: 0
